[package]
name = "rust_mlir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
melior = "0.13.0"
mlir-sys = "0.2.1"
pest = "2.7.5"
pest_derive = "2.7.5"
